"""CodeRabbit configuration generator."""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field


@dataclass
class CodeRabbitConfig:
    """Configuration for CodeRabbit."""

    language: str = "pt-BR"
    tone: str = "professional"
    auto_review: bool = True
    drafts: bool = False
    base_branches: list[str] = field(default_factory=lambda: ["main", "staging"])
    path_filters: list[str] = field(
        default_factory=lambda: [
            "!**/.aios-core/**",
            "!**/.claude/**",
            "!**/node_modules/**",
            "!**/__pycache__/**",
        ]
    )
    review_profile: str = "assertive"


class CodeRabbitGenerator:
    """Generates .coderabbit.yaml configuration."""

    def generate(self, config: CodeRabbitConfig | None = None) -> str:
        """Generate .coderabbit.yaml content."""
        cfg = config or CodeRabbitConfig()

        filters = "\n".join(f'      - "{f}"' for f in cfg.path_filters)
        base_branches = "\n".join(f"      - {b}" for b in cfg.base_branches)

        return f"""# CodeRabbit Configuration
# Generated by NEO-AIOS

language: "{cfg.language}"

tone_instructions: "{cfg.tone}"

early_access: true

reviews:
  profile: "{cfg.review_profile}"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: {str(cfg.auto_review).lower()}
    drafts: {str(cfg.drafts).lower()}
    base_branches:
{base_branches}
  path_filters:
{filters}

chat:
  auto_reply: true
"""
